ii) Find the cosine similarity between documents? Identify the two documents that are most similar.

In [1]:
import numpy as np
# import pandas as pd
import math
# import cosine_similarity from sklearn module 
from sklearn.metrics.pairwise import cosine_similarity


In [2]:
# occurances of layoff in d3
word_occurances_d3 = 23

In [3]:
term_frequency_d3 = 12/ word_occurances_d3


i) Tf IDF value of D3

In [8]:
# IDF_value
IDF_value = math.log(6/3, 2)
TF_IDF_D2 = term_frequency_d3 * IDF_value
print("TF IDF is", TF_IDF_D2)

TF IDF is 0.5217391304347826


ii) cosine similarity

Matrix representation of the table/data

In [10]:
matrix_table = np.array([[19, 12, 4, 6, 0],
                 [0, 2, 0, 0, 14],
                 [8, 0, 3, 12, 0],
                 [0, 5, 10, 0, 1],
                 [0, 0, 0, 0, 4],
                 [4, 19, 2, 6, 0]])

In [11]:
cosine_similarity_matrix_table = cosine_similarity(matrix_table)
print(cosine_similarity_matrix_table)

[[1.         0.07190658 0.67881986 0.37747408 0.         0.72207718]
 [0.07190658 1.         0.         0.15118579 0.98994949 0.13158324]
 [0.67881986 0.         1.         0.18142875 0.         0.3656746 ]
 [0.37747408 0.15118579 0.18142875 1.         0.08908708 0.50170051]
 [0.         0.98994949 0.         0.08908708 1.         0.        ]
 [0.72207718 0.13158324 0.3656746  0.50170051 0.         1.        ]]


From the above table of cosine similarity if the given matrix table, D1 and D6 are the most similar documents.

iii) in word doc